const swaggerUI = require('swagger-ui-express');
const swaggerJsDoc = require('swagger-jsdoc');

const options = {
    swaggerDefinition: {
        openapi: '3.0.1',
        info: {
            title: 'Flowers API',
            version: '1.0.0',
            description: ' Flowers Express API with autogenerated swagger doc',
        },
        "components": {
            "securitySchemes": {
                "bearerAuth": {
                    "type": "http",
                    "scheme": "bearer",
                    "bearerFormat": "Bearer"
                }
            }
        },
        security: [
            {
                bearerAuth: []
            }
        ],
        servers: [{
            url: '/api/'
        }],

        paths: {
            '/users': {
                get: {
                    tags: ['users'],
                    summary: ['Get All User'],
                    description: 'This can only be done by the logged in Admin.',
                    operationId: 'get userId if admin',
                    'responses': {
                        '200': {
                            'description': 'user logged in successfully',
                        },
                        '400': {
                            'description': 'bad request',
                        }
                    },
                }

            },
        },
    },
    apis: [],
};


const specs = swaggerJsDoc(options);
module.exports = (app) => {
    app.use('/api-docs', swaggerUI.serve, swaggerUI.setup(specs));
};
